package com.aitp.dlife.domain.enumeration;

/**
 * The PointEventType enumeration.
 */
public enum PointEventType {
    SALUTE, LOGIN, MESSAGE, MESSAGEWITHIMAGE, REPLY, REPLYWITHIMAGE, JIONACTION, FOCUS, NEWFUN, CARD, CARDWITHIMAGE, PUBILSHACTION, PUBILSHQUESTION, RECHARGE, SYSRECHARGE, REDEEM
}
