package com.aitp.dlife.domain.enumeration;

/**
 * The PointEventType enumeration.
 */
public enum PointEventType {
    SALUTE, LOGIN, MESSAGE, REPLY, JIONACTION, FOCUS, NEWFUN, CARD, RECHARGE, SYSRECHARGE, REDEEM, MESSAGEWITHIMAGE, REPLYWITHIMAGE, CARDWITHIMAGE, PUBILSHACTION, PUBILSHQUESTION
}
